export const datas = [
  {
    id: 1,

    question: "Level",
    name: "level",
    options: ["All", "Junior", "Middle", "Senior"],
  },
  {
    id: 2,
    question: "Position",
    name: "position",
    options: [
      "All",
      "Front-end Developer",
      "Back-end Developer",
      "Full Stack Developer",
      "Mobile Application Developer (Android)",
      "Mobile Application Developer (iOS)",
      "Mobile Application Developer (Flutter)",
      "Embedded Software Developer",
      "Game Developer",
      "Cyber Security",
      "Project Manager",
      "Team / Tech Lead",
      "Software Architect",
      "Data Scientist",
      "Data Analyst",
      "Data Engineer",
      "SAP/ABAP",
      "Machine Learning Engineer",
      "Network & System Engineer",
      "Database Administrator (DBA)",
      "DevOps Engineer",
      "Big Data Engineer",
      "Business Analyst",
      "Software Development Manager / Engineering Manager",
      "QA / Manuel Test",
      "QA / Automation",
      "IT Manager",
      "CTO",
    ],
  },
  {
    id: 3,
    question: "Experience",
    name: "experience",
    options: [
      "All",
      "0 - 1 Yıl",
      "1 - 3 Yıl",
      "3 - 5 Yıl",
      "5 - 7 Yıl",
      "7 - 10 Yıl",
      "10 - 12 Yıl",
      "12 - 14 Yıl",
      "15 Yıl ve üzeri"
    ],
  },
  {
    id: 4,
    question: "City",
    name: "city",
    options: [
      "All",
      "İstanbul",
      "Ankara",
      "İzmir",
      "Adana",
      "Adıyaman",
      "Afyonkarahisar",
      "Ağrı",
      "Aksaray",
      "Amasya",
      "Antalya",
      "Ardahan",
      "Artvin",
      "Aydın",
      "Balıkesir",
      "Bartın",
      "Batman",
      "Bayburt",
      "Bilecik",
      " Bingöl",
      "Bitlis",
      "Bolu",
      "Burdur",
      "Bursa",
      "Çanakkale",
      "Çankırı",
      "Çorum",
      "Denizli",
      "Diyarbakır",
      "Düzce",
      "Edirne",
      "Elazığ",
      "Erzincan",
      "Erzurum",
      "Eskişehir",
      "Gaziantep",
      "Giresun",
      "Gümüşhane",
      "Hakkari",
      "Hatay",
      "Iğdır",
      "Isparta",
      "Kahramanmaraş",
      "Karabük",
      "Karaman",
      "Kars",
      "Kastamonu",
      "Kayseri",
      "Kırıkkale",
      "Kırklareli",
      "Kırşehir",
      "Kilis",
      "Kocaeli",
      "Konya",
      "Kütahya",
      "Malatya",
      "Manisa",
      "Mardin",
      "Mersin",
      "Muğla",
      "Muş",
      "Nevşehir",
      "Niğde",
      "Ordu",
      "Osmaniye",
      "Rize",
      "Sakarya",
      "Samsun",
      "Siirt",
      "Sinop",
      "Sivas",
      "Şanlıurfa",
      "Şırnak",
      "Tekirdağ",
      "Tokat",
      "Trabzon",
      "Tunceli",
      "Uşak",
      "Van",
      "Yalova",
      "Yozgat",
      "Zonguldak",
    ],
  },
  {
    id: 5,
    question: "Work Type",
    name: "work_type",
    options: ["All","Remote", "Hibrit (Ofis + Remote)", "Ofis"],
  },
  {
    id: 6,
    question: "Company size",
    name: "company_size",
    options: [
      "All",
      "1 - 5 Kişi",
      "5 - 10 Kişi",
      "10 - 20 Kişi",
      "20 - 50 Kişi",
      "50 - 100 Kişi",
      "100 - 250 Kişi",
      "250+",
    ],
  },
  {
    id: 7,
    question: "Company",
    name: "company",
    options: [
      "All",
      "Savunma Sanayi",
      "Holding",
      "Yazılım Evi & Danışmanlık",
      "Turizm",
      "Kurumsal",
      "Banka",
      "Startup",
      "E-Ticaret",
      "Lojistik",
      "Oyun",
      "Outsource",
      "ERP",
      "Dijital / Reklam Ajansı",
      "Finans",
      "Otomotiv",
      "Fintech",
      "Telekonumikasyon",
      "Kamu",
      "Eğitim"
    ],
  },
];
